name: Test json

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/checkout@v3
      with:
        python-version: 3.7

    - name: Test json
      run: |
        python3 json_test.py