name: Test json

on: [push]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      with:
        python-version: 3.10

    - name: Test json
      run: |
        python3 json_test.py